name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]*'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build JAR and Release
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests --file pom.xml
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/*.jar
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}